context:
  version: 5.2.5
package:
  name: xz
  version: '{{ version }}'
source:
  url: http://downloads.sourceforge.net/project/lzmautils/xz-{{ version }}.tar.bz2
  sha256: 5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df
  patches:
    - 0001-Add-vs2008-support-via-cmake.patch
    - 0002-Add-gettimeofday-for-VS2008.patch
build:
  number: 1
requirements:
  build:
    - '{{ compiler("c") }}'
    - sel(win and vc<14): c99-to-c89
    - sel(win): cmake
    - sel(win): ninja
    - sel(not win): make
    - sel(not win): automake
    - sel(not win): libtool
  host:
    - sel(win and vc<14): msinttypes
features:
  - name: static
    default: false
about:
  home: http://tukaani.org/xz/
  license: LGPL-2.1 and GPL-2.0
  license_file: COPYING
  summary: Data compression software with high compression ratio
  description: "XZ Utils is free general-purpose data compression software with a high\ncompression ratio. XZ Utils were written for POSIX-like systems, but also\nwork on some not-so-POSIX systems.\n"
  doc_url: http://tukaani.org/xz/
  doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
  dev_url: http://git.tukaani.org/
extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - mingwandroid
    - nehaljwani
    - scopatz
