context:
  name: libsolv
  version: 0.7.16
  sha256: ed1753255792e9ae0582a1904c4baba5801036ef3efd559b65027e14ee1ea282
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/openSUSE/libsolv/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'
  patches:
    - sel(win): win_export_and_static_build.patch
build:
  number: 0
requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - sel(not win): make
    - sel(win): ninja
    - cmake
  host:
    - zlib-static
features:
  - name: static
    default: false
about:
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
