context:
  version: 1.9.0
package:
  name: libssh2
  version: '{{ version }}'
source:
  url: https://www.libssh2.org/download/libssh2-{{ version }}.tar.gz
  sha256: d5fb8bd563305fd1074dda90bd053fb2d29fc4bce048d182f96eaa466dfadafd
  patches:
    - 0001-libssh2-1.9.0-CVE-2019-17498.patch
    - 246c7cb0184b9e1a882c753b412825799c7a9118.patch
build:
  number: 5
requirements:
  build:
    - sel(win): cmake-binary
    - sel(not win): cmake-no-system
    - sel(not (osx and arm64)): '{{ compiler("c") }}'
    - sel(osx and arm64): '{{ compiler("clang_bootstrap") }}'
    - sel(win): ninja
    - sel(unix): make
  host:
    - openssl-static
    - zlib-static
  run:
    - openssl-static
    - zlib-static
features:
  - name: static
    default: false
about:
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
  description: "libssh2 is a library implementing the SSH2 protocol, available under the revised BSD license.\n"
  dev_url: https://github.com/libssh2/libssh2
extra:
  recipe-maintainers:
    - shadowwalkersb
    - nehaljwani
    - ocefpaf
