context:
  version: 1.16.1
package:
  name: c-ares
  version: '{{ version }}'
source:
  url: https://c-ares.haxx.se/download/c-ares-{{ version }}.tar.gz
  sha256: d08312d0ecc3bd48eee0a4cc0d2137c9f194e0a28de2028928c0f6cae85f86ce
build:
  number: 0
requirements:
  build:
    - '{{ compiler("c") }}'
    - sel(win): cmake
    - sel(unix): cmake-no-system
    - sel(unix): ninja
features:
  - name: static
    default: false
about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
