context:
  version: 1.0.8
package:
  name: bzip2
  version: '{{ version }}'
source:
  url: https://sourceware.org/pub/bzip2/bzip2-{{ version }}.tar.gz
  sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269
  patches:
    - 0001-cross.patch
build:
  number: 0
requirements:
  build:
    - '{{ compiler("c") }}'
    - sel(win): jom
    - sel(unix): make
features:
  - name: static
    default: false
about:
  home: http://www.bzip.org/
  license_family: BSD
  license_file: LICENSE
  license: bzip2-1.0.6
  summary: high-quality data compressor
  description: "Bzip2 is a freely available high-quality data compressor. It typically\ncompresses files to within 10% to 15% of the best available techniques,\nwhilst being around twice as fast at compression and six times faster\nat decompression.\n"
  doc_url: http://www.bzip.org/docs.html
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - pelson
    - jlanga
    - mingwandroid
    - msarahan
