context:
  version: 1.1.1i
package:
  name: openssl
  version: '{{ version }}'
source:
  url: http://www.openssl.org/source/openssl-{{ version }}.tar.gz
  sha256: e8be6a35fe41d10603c3cc635e93289ed00bf34b79671a3a4de64fcee00d5242
  patches:
    - 0001-Don-t-use-USE_BCRYPTGENRANDOM-for-VS-older-than-2015.patch
build:
  number: 0
features:
  - name: static
    default: false
outputs:
  - package:
      name: openssl
    build:
      no_link:
        - sel(linux): lib/libcrypto.so.1.1
        - sel(osx): lib/libcrypto.1.1.dylib
    requirements:
      build:
        - '{{ compiler("c") }}'
        - sel(win): nasm
        - sel(unix): make
        - sel(not win): perl
      host:
        - sel(win): perl
      run:
        - ca-certificates
about:
  home: http://www.openssl.org/
  license_file: LICENSE
  license: OpenSSL
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.1.1/
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
    - carlodri
