context:
  name: zstd
  version: 1.4.8
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/facebook/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32478297ca1500211008d596276f5367c54198495cf677e9439f4791a4c69f24
  patches:
    - sel(aarch64): utime-aarch64.patch
build:
  number: 2
  skip:
    - win
requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - sel(win): msinttypes
    - sel(unix): make
    - sel(win): ninja
    - cmake
features:
  - name: static
    default: false
  - name: programs
    default: false
about:
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
  description: "Zstandard is a real-time compression algorithm, providing high compression\nratios. It offers a very wide range of compression / speed trade-off, while\nbeing backed by a very fast decoder. It also offers a special mode for\nsmall data, called dictionary compression, and can create dictionaries from\nany sample set. Zstandard library is provided as open source software using\na BSD license.\n"
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  dev_url: https://github.com/facebook/zstd
extra:
  recipe-maintainers:
    - rmax
    - msarahan
    - xhochy
