context:
  pkg_name: lz4-c
  name: lz4
  version: 1.9.3
package:
  name: '{{ pkg_name }}'
  version: '{{ version }}'
source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 030644df4611007ff7dc962d981f390361e6c97a34e5cbc393ddfbe019ffe2c1
  patches:
    - patches/0001-Add-WindowsTargetPlatformVersion-of-10.0-and-lz4-exe.1.patch
    - patches/0001-Add-WindowsTargetPlatformVersion-of-10.0-and-lz4-exe.2.patch
build:
  number: 0
requirements:
  build:
    - '{{ compiler("c") }}'
    - sel(not win): '{{ compiler("cxx") }}'
    - sel(not win): make
    - sel(unix): patch
    - sel(win): m2-patch
    - sel(win): m2-gcc-libs
features:
  - name: static
    default: false
about:
  home: https://www.lz4.org
  license: BSD-2-Clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
  description: "LZ4 is lossless compression algorithm, providing compression speed at 400\nMB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,\nwith speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression\nderivative, called LZ4_HC, is available, trading customizable CPU time for\ncompression ratio. LZ4 library is provided as open source software using a\nBSD license.\n"
extra:
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
