context:
  version: 1.2.11
package:
  name: zlib
  version: '{{ version }}'
source:
  url: http://zlib.net/zlib-{{ version }}.tar.gz
  sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
build:
  number: 0
requirements:
  build:
    - '{{ compiler("c") }}'
    - sel(win): cmake
    - sel(unix): make
features:
  - name: static
    default: false
about:
  home: http://zlib.net/
  license: Zlib
  summary: Massively spiffy yet delicately unobtrusive compression library
  license_family: Other
  license_file: license.txt
  description: "zlib is designed to be a free, general-purpose, lossless data-compression\nlibrary for use on virtually any computer hardware and operating system.\n"
  doc_url: http://zlib.net/manual.html
  dev_url: https://github.com/madler/zlib
extra:
  recipe-maintainers:
    - groutr
    - msarahan
    - ocefpaf
    - mingwandroid
