context:
  version: 3.5.1
package:
  name: libarchive
  version: '{{ version }}'
source:
  url: https://github.com/libarchive/libarchive/archive/v{{ version }}.tar.gz
  sha256: 6d92e669e259a55a0119c135873469778f2718acbe605717f9d341487b4d0cba
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
    - patches/0008-VC9-compatibility-remove-C99.patch
    - patches/0009-CMake-Force-Multi-threaded-DLL-runtime.patch
build:
  number: 0
  skip:
    - win and vc<14
requirements:
  build:
    - '{{ compiler("c") }}'
    - sel(win and vc<14): msinttypes
    - sel(unix): autoconf
    - sel(unix): automake
    - sel(unix): libtool
    - sel(unix): pkg-config
    - sel(win): cmake
    - sel(unix): make
    - sel(win): ninja
    - sel(win): m2-patch
  host:
    - sel(win and vc<14): msinttypes
    - sel(osx): libiconv
  run:
    - sel(osx): libiconv
features:
  - name: zlib
    default: true
    requirements:
      host:
        - zlib-static
      run:
        - zlib-static
  - name: zstd
    default: true
    requirements:
      host:
        - zstd-static
      run:
        - zstd-static
  - name: openssl
    default: true
    requirements:
      host:
        - openssl-static
      run:
        - openssl-static
  - name: lzo
    default: true
    requirements:
      host:
        - lzo-static
      run:
        - lzo-static
  - name: xz
    default: true
    requirements:
      host:
        - xz-static
      run:
        - xz-static
  - name: bzip2
    default: true
    requirements:
      host:
        - bzip2-static
      run:
        - bzip2-static
  - name: lz4
    default: true
    requirements:
      host:
        - lz4-c-static
      run:
        - lz4-c-static
  - name: xml2
    default: true
    requirements:
      host:
        - libxml2-static
      run:
        - libxml2-static
  - name: static
    default: false
about:
  home: http://www.libarchive.org/
  summary: Multi-format archive and compression library
  license: BSD-2-Clause
  license_file: COPYING
  license_family: BSD
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
